require 'ebay/types/address_attribute'

module Ebay # :nodoc:
  module Types # :nodoc:
    # == Attributes
    #  text_node :name, 'Name'
    #  text_node :street, 'Street'
    #  text_node :street1, 'Street1'
    #  text_node :street2, 'Street2'
    #  text_node :city_name, 'CityName'
    #  text_node :county, 'County'
    #  text_node :state_or_province, 'StateOrProvince'
    #  text_node :country, 'Country'
    #  text_node :country_name, 'CountryName'
    #  text_node :phone, 'Phone'
    #  text_node :phone_country_code, 'PhoneCountryCode'
    #  text_node :phone_country_prefix, 'PhoneCountryPrefix'
    #  text_node :phone_area_or_city_code, 'PhoneAreaOrCityCode'
    #  text_node :phone_local_number, 'PhoneLocalNumber'
    #  text_node :phone2_country_code, 'Phone2CountryCode'
    #  text_node :phone2_country_prefix, 'Phone2CountryPrefix'
    #  text_node :phone2_area_or_city_code, 'Phone2AreaOrCityCode'
    #  text_node :phone2_local_number, 'Phone2LocalNumber'
    #  text_node :postal_code, 'PostalCode'
    #  text_node :address_id, 'AddressID'
    #  text_node :address_owner, 'AddressOwner'
    #  text_node :address_status, 'AddressStatus'
    #  text_node :external_address_id, 'ExternalAddressID'
    #  text_node :international_name, 'InternationalName'
    #  text_node :international_state_and_city, 'InternationalStateAndCity'
    #  text_node :international_street, 'InternationalStreet'
    #  text_node :company_name, 'CompanyName'
    #  text_node :address_record_type, 'AddressRecordType'
    #  text_node :first_name, 'FirstName'
    #  text_node :last_name, 'LastName'
    #  text_node :phone2, 'Phone2'
    #  text_node :address_usage, 'AddressUsage'
    #  text_node :reference_id, 'ReferenceID'
    #  object_node :address_attribute, 'AddressAttribute', :class => AddressAttribute
    class Address
      include XML::Mapping
      include Initializer
      root_element_name 'Address'
      text_node :name, 'Name'
      text_node :street, 'Street'
      text_node :street1, 'Street1'
      text_node :street2, 'Street2'
      text_node :city_name, 'CityName'
      text_node :county, 'County'
      text_node :state_or_province, 'StateOrProvince'
      text_node :country, 'Country'
      text_node :country_name, 'CountryName'
      text_node :phone, 'Phone'
      text_node :phone_country_code, 'PhoneCountryCode'
      text_node :phone_country_prefix, 'PhoneCountryPrefix'
      text_node :phone_area_or_city_code, 'PhoneAreaOrCityCode'
      text_node :phone_local_number, 'PhoneLocalNumber'
      text_node :phone2_country_code, 'Phone2CountryCode'
      text_node :phone2_country_prefix, 'Phone2CountryPrefix'
      text_node :phone2_area_or_city_code, 'Phone2AreaOrCityCode'
      text_node :phone2_local_number, 'Phone2LocalNumber'
      text_node :postal_code, 'PostalCode'
      text_node :address_id, 'AddressID'
      text_node :address_owner, 'AddressOwner'
      text_node :address_status, 'AddressStatus'
      text_node :external_address_id, 'ExternalAddressID'
      text_node :international_name, 'InternationalName'
      text_node :international_state_and_city, 'InternationalStateAndCity'
      text_node :international_street, 'InternationalStreet'
      text_node :company_name, 'CompanyName'
      text_node :address_record_type, 'AddressRecordType'
      text_node :first_name, 'FirstName'
      text_node :last_name, 'LastName'
      text_node :phone2, 'Phone2'
      text_node :address_usage, 'AddressUsage'
      text_node :reference_id, 'ReferenceID'
      object_node :address_attribute, 'AddressAttribute', :class => AddressAttribute
    end
  end
end


